//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lateetud.NServiceBus.DAL.ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMARTEntities : DbContext
    {
        public SMARTEntities()
            : base("name=SMARTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SmartOcr> SmartOcrs { get; set; }
        public virtual DbSet<SmartRpa> SmartRpas { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SmartOcr_InsertUpdate(string mode, string serviceName, string messageId, string requestId, string message, string status)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var serviceNameParameter = serviceName != null ?
                new ObjectParameter("ServiceName", serviceName) :
                new ObjectParameter("ServiceName", typeof(string));
    
            var messageIdParameter = messageId != null ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(string));
    
            var requestIdParameter = requestId != null ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SmartOcr_InsertUpdate", modeParameter, serviceNameParameter, messageIdParameter, requestIdParameter, messageParameter, statusParameter);
        }
    
        public virtual ObjectResult<SmartOcrByRequestId_Select_Result> SmartOcrByRequestId_Select(string requestId)
        {
            var requestIdParameter = requestId != null ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SmartOcrByRequestId_Select_Result>("SmartOcrByRequestId_Select", requestIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SmartRpa_InsertUpdate(string mode, string serviceName, string messageId, string requestId, string message, string status)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var serviceNameParameter = serviceName != null ?
                new ObjectParameter("ServiceName", serviceName) :
                new ObjectParameter("ServiceName", typeof(string));
    
            var messageIdParameter = messageId != null ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(string));
    
            var requestIdParameter = requestId != null ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SmartRpa_InsertUpdate", modeParameter, serviceNameParameter, messageIdParameter, requestIdParameter, messageParameter, statusParameter);
        }
    
        public virtual ObjectResult<SmartRpaByRequestId_Select_Result> SmartRpaByRequestId_Select(string requestId)
        {
            var requestIdParameter = requestId != null ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SmartRpaByRequestId_Select_Result>("SmartRpaByRequestId_Select", requestIdParameter);
        }
    }
}
