//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lateetud.NServiceBus.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NECGeneralAgentEntities : DbContext
    {
        public NECGeneralAgentEntities()
            : base("name=NECGeneralAgentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeneralAgent> GeneralAgents { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GeneralAgent_InsertUpdate(string mode, string generalAgentID, string message, string status)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var generalAgentIDParameter = generalAgentID != null ?
                new ObjectParameter("GeneralAgentID", generalAgentID) :
                new ObjectParameter("GeneralAgentID", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GeneralAgent_InsertUpdate", modeParameter, generalAgentIDParameter, messageParameter, statusParameter);
        }
    
        public virtual ObjectResult<GeneralAgentByGeneralAgentID_Select_Result> GeneralAgentByGeneralAgentID_Select(string generalAgentID)
        {
            var generalAgentIDParameter = generalAgentID != null ?
                new ObjectParameter("GeneralAgentID", generalAgentID) :
                new ObjectParameter("GeneralAgentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralAgentByGeneralAgentID_Select_Result>("GeneralAgentByGeneralAgentID_Select", generalAgentIDParameter);
        }
    }
}
