//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lateetud.NServiceBus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueMap
    {
        public long QueueMapID { get; set; }
        public long SubscriberQueueID { get; set; }
        public long PublisherQueueID { get; set; }
        public string MessageType { get; set; }
    
        public virtual Queue Queue { get; set; }
        public virtual Queue Queue1 { get; set; }
    }
}
